---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-quota-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: resource-quota-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: resource-quota-manager
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resource-quota-manager
  name: resource-quota-manager
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: resource-quota-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: resource-quota-manager
    spec:
      containers:
        - args:
            - --v=5
            - --namespace-selector=virtualization.kubesphere.io/enable=true
            - --cpu-limit=24
            - --mem-limit=48Gi
            - --storage-limit=600Gi
          command:
            - /manager
          image: stoneshiyunify/quota-manager:latest
          imagePullPolicy: IfNotPresent
          name: quota-manager
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: resource-quota-manager